#!/bin/bash
#
# This is a place-holder to run an anaconda shell which is installed
# inside a docker image. This workaround is needed for use by
# programs/scripts that are not run within a full shell environment.

docker run -it \
           --rm \
           --name anaconda \
           --volume=$PWD:/opt/data \
           --volume=/tmp/.X11-unix:/tmp/.X11-unix \
           -e DISPLAY=unix$DISPLAY \
           -e LANG \
           continuumio/anaconda /bin/bash
