#!/bin/bash
#
# This is a place-holder to run mencoder which is installed inside a
# docker image. This workaround is needed for use by programs/scripts
# that are not run within a full shell environment.

docker run -it \
           --rm \
           --name mencoder \
           --volume=$PWD:/home/mencoder/video \
           -u $UID \
           hainesr/mencoder "$@"
